version: '2'

services:
  postgresdb:
    build: envirocar-postgres/
    expose:
      - 5432
  mongodb:
    build: envirocar-mongo/
    expose:
      - 27017
  importer:
    build: envirocar-importer/
    environment:
      - MONGO_PORT=27017
      - MONGO_DB=enviroCar
    links:
      - mongodb:mongo
      - postgresdb:postgres
